sudo: required

services:
    - docker

language: c

env:
    matrix:
        - DOCKER_IMG=okuoku/yunibase:testing
        - DOCKER_IMG=okuoku/yunibase:testing-fedora
        - DOCKER_IMG=okuoku/yunibase:testing-java
        - DOCKER_IMG=okuoku/yunibase:testing-ubuntu32
        - DOCKER_IMG=okuoku/yunibase:testing-alpine
        - DOCKER_IMG=okuoku/yunibase:testing-fedora

script:
    - sudo integration/buildhost-qemu-static/register.sh
    - docker pull $DOCKER_IMG
    - cmake -DIMAGE=$DOCKER_IMG -P integration/buildhost-docker-linux/test-on-docker.cmake

